### ISSUE TITLE
console error

### ISSUE THREAD

**Issue by antibitcoin** [Korbsti/Mythical-Races#5]
I did not edit any configuration files.

[01:20:24 ERROR]: There's an incorrect configuration in the race: Sentinel. Please correct it. If the race is not the problem, inspect the class: Swordmaster. It could be the source of the issue.
[01:20:24 WARN]: java.lang.IndexOutOfBoundsException: Index 3 out of bounds for length 3
[01:20:24 WARN]:        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
[01:20:24 WARN]:        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
[01:20:24 WARN]:        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
[01:20:24 WARN]:        at java.base/java.util.Objects.checkIndex(Objects.java:359)
[01:20:24 WARN]:        at java.base/java.util.ArrayList.get(ArrayList.java:427)
[01:20:24 WARN]:        at MythicalRaces-2.3.8-SE-V1-out.jar//src.me.korbsti.mythicalraces.other.h.a(Unknown Source)
[01:20:24 WARN]:        at MythicalRaces-2.3.8-SE-V1-out.jar//src.me.korbsti.mythicalraces.a.run(Unknown Source)
[01:20:24 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[01:20:24 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
[01:20:24 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1479)
[01:20:24 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
[01:20:24 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1393)
[01:20:24 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1170)
[01:20:24 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[01:20:24 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[01:20:27 ERROR]: There's an incorrect configuration in the race: Sentinel. Please correct it. If the race is not the problem, inspect the class: Swordmaster. It could be the source of the issue.
[01:20:27 WARN]: java.lang.IndexOutOfBoundsException: Index 3 out of bounds for length 3
[01:20:27 WARN]:        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
[01:20:27 WARN]:        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
[01:20:27 WARN]:        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
[01:20:27 WARN]:        at java.base/java.util.Objects.checkIndex(Objects.java:359)
[01:20:27 WARN]:        at java.base/java.util.ArrayList.get(ArrayList.java:427)
[01:20:27 WARN]:        at MythicalRaces-2.3.8-SE-V1-out.jar//src.me.korbsti.mythicalraces.other.h.a(Unknown Source)
[01:20:27 WARN]:        at MythicalRaces-2.3.8-SE-V1-out.jar//src.me.korbsti.mythicalraces.a.run(Unknown Source)
[01:20:27 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[01:20:27 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
[01:20:27 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1479)
[01:20:27 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
[01:20:27 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1393)
[01:20:27 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1170)
[01:20:27 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[01:20:27 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[01:20:30 ERROR]: There's an incorrect configuration in the race: Sentinel. Please correct it. If the race is not the problem, inspect the class: Swordmaster. It could be the source of the issue.
[01:20:30 WARN]: java.lang.IndexOutOfBoundsException: Index 3 out of bounds for length 3
[01:20:30 WARN]:        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
[01:20:30 WARN]:        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
[01:20:30 WARN]:        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
[01:20:30 WARN]:        at java.base/java.util.Objects.checkIndex(Objects.java:359)
[01:20:30 WARN]:        at java.base/java.util.ArrayList.get(ArrayList.java:427)
[01:20:30 WARN]:        at MythicalRaces-2.3.8-SE-V1-out.jar//src.me.korbsti.mythicalraces.other.h.a(Unknown Source)
[01:20:30 WARN]:        at MythicalRaces-2.3.8-SE-V1-out.jar//src.me.korbsti.mythicalraces.a.run(Unknown Source)
[01:20:30 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[01:20:30 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
[01:20:30 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1479)
[01:20:30 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
[01:20:30 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1393)
[01:20:30 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1170)
[01:20:30 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[01:20:30 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[01:20:34 INFO]: [LP] sly9909 already inherits from immortal in context global.
[01:20:36 ERROR]: There's an incorrect configuration in the race: Sentinel. Please correct it. If the race is not the problem, inspect the class: Swordmaster. It could be the source of the issue.
[01:20:36 WARN]: java.lang.IndexOutOfBoundsException: Index 3 out of bounds for length 3
[01:20:36 WARN]:        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
[01:20:36 WARN]:        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
[01:20:36 WARN]:        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
[01:20:36 WARN]:        at java.base/java.util.Objects.checkIndex(Objects.java:359)
[01:20:36 WARN]:        at java.base/java.util.ArrayList.get(ArrayList.java:427)
[01:20:36 WARN]:        at MythicalRaces-2.3.8-SE-V1-out.jar//src.me.korbsti.mythicalraces.other.h.a(Unknown Source)
[01:20:36 WARN]:        at MythicalRaces-2.3.8-SE-V1-out.jar//src.me.korbsti.mythicalraces.a.run(Unknown Source)
[01:20:36 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[01:20:36 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
[01:20:36 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1479)
[01:20:36 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
[01:20:36 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1393)
[01:20:36 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1170)
[01:20:36 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[01:20:36 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[01:20:39 ERROR]: There's an incorrect configuration in the race: Sentinel. Please correct it. If the race is not the problem, inspect the class: Swordmaster. It could be the source of the issue.

**Comment by Korbsti** [comment]
Youre not using the latest version, try deleting the MythicalRaces folder and restart, if not join the discord server and we can discuss more there
